version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - travisdock
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: billboard.js
    versions:
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.2.6
    - 3.0.0
    - 3.0.1
    - 3.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: react-table
    versions:
    - 7.6.3
  - dependency-name: react-spinners
    versions:
    - 0.10.4
  - dependency-name: enzyme-to-json
    versions:
    - 3.6.1
