language: node_js
branches:
  only:
    - production
    - staging
before_script:
  - if [ "$TRAVIS_BRANCH" == "production" ]; then npm install -g firebase-tools; fi
script:
  - npm run test:ci
  - npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - if [ "$TRAVIS_BRANCH" == "production" ]; then npm run-script build; fi
  - npm run test
after_success:
  - if [ "$TRAVIS_BRANCH" == "production" ]; then firebase deploy --only hosting:sum-finance --token=${FIREBASE_API_TOKEN}; fi